#spring:
#  config:
#    import: optional:configserver:http://localhost:8888
#  application:
#    name: customer-service

spring:
  cloud:
    config:
      enabled: false  # Disable Config Server entirely

  datasource:
    url:

server:
  port: 8090